# Default values for deployment.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2
pullPolicy: Always
image: registry.bottled.codes/swytch/once
host: once.getswytch.com

auth:
  signinUrl: https://auth.getswytch.com/login
  allowedRoles: user
  authUrl: http://swytch-auth.auth.svc.cluster.local/api/auth

secrets:
  stateSecret: this.is.secret

rethinkdb:
  host: rethinkdb
  db: once
  user: once
  password: secret

probes: true
