# Default values for deployment.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
pullPolicy: Always
image: registry.bottled.codes/swytch/once
host: once.getswytch.com

auth:
  signinUrl: https://auth.getswytch.com/login
  allowedRoles: user

secrets:
  stateSecret: this.is.secret
