apiVersion: apps/v1
kind: Deployment
metadata:
  name: swytch-once
spec:
  replicas: {{.Values.replicaCount}}
  strategy:
    rollingUpdate:
      maxSurge: 10%
      maxUnavailable: 50%
  selector:
    matchLabels:
      app: swytch-once
  template:
    metadata:
      name: swytch-once
      labels:
        app: swytch-once
    spec:
      terminationGracePeriodSeconds: 30
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                topologyKey: kubernetes.io/hostname
              weight: 100
      containers:
        - name: swytch-once
          imagePullPolicy: {{ .Values.pullPolicy }}
          env:
            - name: SWYTCH_STATE_SECRET
              valueFrom:
                secretKeyRef:
                  key: state-secret
                  name: swytch-once
            - name: SWYTCH_DEFAULT_LANGUAGE
              value: 'en'
            - name: SWYTCH_SUPPORTED_LANGUAGES
              value: 'en,nl'
            - name: RDB_HOST
              valueFrom:
                secretKeyRef:
                  key: rdb-host
                  name: swytch-once
            - name: RDB_DB
              valueFrom:
                secretKeyRef:
                  key: rdb-db
                  name: swytch-once
            - name: RDB_USER
              valueFrom:
                secretKeyRef:
                  key: rdb-user
                  name: swytch-once
            - name: RDB_PASS
              valueFrom:
                secretKeyRef:
                  key: rdb-password
                  name: swytch-once
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              memory: 1Gi
          image: {{.Values.image}}
