kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: once.getswytch.com
  labels:
    app: swytch-once
  annotations:
    nginx.ingress.kubernetes.io/limit-rps: "5"
    nginx.ingress.kubernetes.io/enable-opentracing: "true"
    nginx.ingress.kubernetes.io/enable-modsecurity: "true"
    nginx.ingress.kubernetes.io/enable-owasp-core-rules: "true"
    cert-manager.io/cluster-issuer: zerossl-production
    cert-manager.io/issue-temporary-certificate: 'true'
    certmanager.k8s.io/cluster-issuer: zerossl-production
    nginx.ingress.kubernetes.io/auth-response-headers: X-Auth-Request-User,X-Auth-Request-Email,X-Auth-Request-Access-Token,Set-Cookie,Authorization
    nginx.ingress.kubernetes.io/auth-signin: {{.Values.auth.signinUrl}}
    nginx.ingress.kubernetes.io/auth-url: {{.Values.auth.authUrl}}?roles=none
spec:
  ingressClassName: nginx
  tls:
    - secretName: tls-app
      hosts:
        - {{.Values.host}}
  rules:
    - host: {{.Values.host}}
      http:
        paths:
          - backend:
              service:
                name: swytch-once
                port:
                  number: 80
            pathType: Prefix
            path: /
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: once-loggedin.getswytch.com
  labels:
    app: swytch-once
  annotations:
    nginx.ingress.kubernetes.io/limit-rps: "5"
    nginx.ingress.kubernetes.io/enable-opentracing: "true"
    nginx.ingress.kubernetes.io/enable-modsecurity: "true"
    nginx.ingress.kubernetes.io/enable-owasp-core-rules: "true"
    cert-manager.io/cluster-issuer: zerossl-production
    cert-manager.io/issue-temporary-certificate: 'true'
    certmanager.k8s.io/cluster-issuer: zerossl-production
    nginx.ingress.kubernetes.io/auth-signin-redirect-param: "rd"
    nginx.ingress.kubernetes.io/auth-response-headers: X-Auth-Request-User,X-Auth-Request-Email,X-Auth-Request-Access-Token,Set-Cookie,Authorization
    nginx.ingress.kubernetes.io/auth-signin: {{.Values.auth.signinUrl}}
    nginx.ingress.kubernetes.io/auth-url: {{.Values.auth.authUrl}}?roles={{.Values.auth.allowedRoles}}
spec:
  ingressClassName: nginx
  tls:
    - secretName: tls-app
      hosts:
        - {{.Values.host}}
  rules:
    - host: {{.Values.host}}
      http:
        paths:
          - backend:
              service:
                name: swytch-once
                port:
                  number: 80
            pathType: Prefix
            path: /app
    - host: {{.Values.host}}
      http:
        paths:
          - backend:
              service:
                name: swytch-once
                port:
                  number: 80
            pathType: Prefix
            path: /api/user
