kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: once.getswytch.com
  labels:
    app: swytch-once
  annotations:
    nginx.ingress.kubernetes.io/limit-rps: "5"
    nginx.ingress.kubernetes.io/enable-opentracing: "true"
    nginx.ingress.kubernetes.io/enable-modsecurity: "true"
    nginx.ingress.kubernetes.io/enable-owasp-core-rules: "true"
    cert-manager.io/cluster-issuer: letsencrypt
    cert-manager.io/issue-temporary-certificate: 'true'
    certmanager.k8s.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: nginx
  tls:
    - secretName: tls-app
      hosts:
        - once.getswytch.com
  rules:
    - host: once.getswytch.com
      http:
        paths:
          - backend:
              service:
                name: swytch-once
                port:
                  number: 80
            pathType: Prefix
            path: /
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: once-loggedin.getswytch.com
  labels:
    app: swytch-once
  annotations:
    nginx.ingress.kubernetes.io/limit-rps: "5"
    nginx.ingress.kubernetes.io/enable-opentracing: "true"
    nginx.ingress.kubernetes.io/enable-modsecurity: "true"
    nginx.ingress.kubernetes.io/enable-owasp-core-rules: "true"
    cert-manager.io/cluster-issuer: letsencrypt
    cert-manager.io/issue-temporary-certificate: 'true'
    certmanager.k8s.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/auth-signin-redirect-param: "rd"
    nginx.ingress.kubernetes.io/auth-response-headers: X-Auth-Request-User,X-Auth-Request-Email,X-Auth-Request-Access-Token,Set-Cookie,Authorization
    nginx.ingress.kubernetes.io/auth-signin: https://auth.bottled.codes/login
    nginx.ingress.kubernetes.io/auth-url: http://swytch-auth.auth.svc.cluster.local/api/auth?roles=admin
spec:
  ingressClassName: nginx
  tls:
    - secretName: tls-app
      hosts:
        - once.getswytch.com
  rules:
    - host: once.getswytch.com
      http:
        paths:
          - backend:
              service:
                name: swytch-once
                port:
                  number: 80
            pathType: Prefix
            path: /app
