kind: Secret
apiVersion: v1
metadata:
  name: swytch-once
stringData:
  state-secret: {{ .Values.secrets.stateSecret }}
  rdb-host: {{.Values.rethinkdb.host}}
  rdb-db: {{.Values.rethinkdb.db}}
  rdb-user: {{.Values.rethinkdb.user}}
  rdb-password: {{.Values.rethinkdb.password}}
