apiVersion: v1
kind: Service
metadata:
  name: swytch-once
  labels:
    app: swytch-once
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: swytch-once
  ipFamilyPolicy: PreferDualStack
