name: Create Preview Environment
on:
  merge_group:
    types:
      - checks_requested
  pull_request:
    branches:
      - main
concurrency:
  group: preview-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true
jobs:
  PreviewDeploy:
    environment: Preview
    name: Deploy Preview
    timeout-minutes: 15
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true

      - uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
        with:
          install: true

      - name: Install DevSpace
        uses: loft-sh/setup-devspace@main

      - name: Install Loft
        uses: loft-sh/setup-loft@v2
        with:
          # version: v1.15.0
          url: https://kube.bottled.codes
          access-key: ${{ secrets.LOFT_ACCESS_KEY }}

      - name: Build image
        run: |
          loft use cluster
          # build the current sha from the current branch
          devspace use namespace once
          devspace build -t ${{ github.sha }} --no-warn

      - name: Create Preview Cluster
        run: |
          loft create vcluster once-preview${{ github.event.pull_request.number }} --project swytch --use --template preview-cluster

      - name: Deploy
        run: |
          devspace use namespace once --no-warn
          devspace deploy --no-warn -t ${{ github.sha }} --skip-build --skip-push \
            --var STATE_SECRET="${{ secrets.STATE_SECRET }}" \
            --var RETHINKDB_PASSWORD="${{ secrets.RETHINKDB_PASSWORD }}" \
            --var AUTH_LOGIN="https://fake-auth.preview${{github.event.pull_request.number}}.once.getswytch.com/login" \
            --var AUTH_URL="https://fake-auth.preview${{github.event.pull_request.number}}.once.getswytch.com/api/auth" \
            --var POSTMARK_API_KEY="${{ secrets.POSTMARK_SANDBOX_API_KEY }}" \
            --var HOST="preview${{ github.event.pull_request.number }}.once.getswytch.com"
          RETHINKDB_ADMIN_PASSWORD=${{ secrets.RETHINKDB_ADMIN_PASSWORD }} devspace run-pipeline db-migrate

      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          number: ${{ github.event.pull_request.number }}
          header: release
          message: |
            Preview environment deployed at: [https://preview${{ github.event.pull_request.number }}.once.getswytch.com](https://preview${{ github.event.pull_request.number }}.once.getswytch.com)
            
            It may take a few minutes for DNS entries and certificates to propagate (you can add `65.108.6.254` to your hosts file).
